# Generated by Django 5.2.3 on 2025-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabha_name', models.CharField(max_length=255)),
                ('sabha_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('country_code', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=100)),
                ('pradesh', models.CharField(max_length=50)),
                ('reference_sant', models.CharField(max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('event_details', models.ManyToManyField(to='core.eventdetail')),
            ],
        ),
    ]
