# Generated by Django 5.2.3 on 2025-06-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='event_details',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_details', to='core.userprofile'),
        ),
    ]
