# Generated by Django 5.2.3 on 2025-06-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dashboardcontent_pradesh_sabhaoption_sant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcontent',
            name='google_drive_embed',
        ),
        migrations.RemoveField(
            model_name='dashboardcontent',
            name='zip_download_link',
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='raw_drive_folder_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='raw_zip_download_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
